demo2/demo2/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('vote/',include('vote.urls',namespace='vote'))

]

demo2/vote/urls.py
from django.conf.urls import url
from . import views
app_name='vote'

urlpatterns = [

    url(r'^$',views.index,name='index'),
    url(r'^detail/(\d+)/$', views.detail, name='detail'),
    url(r'^result/(\d+)/$', views.result, name='result'),
    url(r'^login/$',views.login,name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^regist/$', views.regist, name='regist'),

]

demo2/vote/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Question(models.Model):
    desc=models.CharField(max_length=30)
    create_time=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.desc


class Choice(models.Model):
    desc=models.CharField(max_length=20)
    num=models.IntegerField(default=0)
    question=models.ForeignKey(Question,on_delete=models.CASCADE)

    def __str__(self):
        return self.desc


class PullsUser(User):
    telepone=models.CharField(max_length=11)

demo2/vote/forms.py
from django import forms

class LoginForm(forms.Form):
    username=forms.CharField(label="用户名",max_length=20,required=True,widget=forms.TextInput(attrs={'id':'username','class':'form-control','placeholder':'输入用户名'}))
    password=forms.CharField(label="密码",max_length=20,required=True,widget=forms.PasswordInput(attrs={'id':'password','class':'form-control','placeholder':'输入密码'}))

demo2/vote/views.py
from django.shortcuts import render,redirect,reverse,get_object_or_404
from django.http import HttpResponse
from .models import *
from django.contrib.auth import login as lgi,logout as lgo,authenticate
from .forms import LoginForm
# Create your views here.
def checklogin(fun):
    def check(requst,*args):
        if requst.user and requst.user.is_authenticated:
            return fun(requst,*args)
        else:
            return redirect(reverse("vote:login"))
    return check

@checklogin
def index(request):
    desc=Question.objects.all()

    return render(request,'vote/index.html',locals())
@checklogin
def detail(request,id):
    desc=Question.objects.get(pk=id)
    if request.method == 'GET':
        return render(request,'vote/detail.html',locals())
    elif request.method == "POST":
        choiced=request.POST.get('choice')
        choice=Choice.objects.get(pk=choiced)
        choice.num += 1
        choice.save()
        return redirect(reverse('vote:result',args=(id,)))
@checklogin
def result(request,id):
    desc=Question.objects.get(pk=id)
    return render(request,'vote/result.html',locals())


def login(request):
    if request.method == "GET":
        form = LoginForm()
        return render(request,'vote/login.html',{'form':form})
    elif request.method == 'POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(request,username=username,password=password)
        if user:
            lgi(request,user)
            return redirect(reverse("vote:index"))
        else:
            return render(request,'vote/login.html',{"errors":"登陆失败"})

        # form = LoginForm(request.POST)
        #
        # username=request.POST.get('username')
        # password=request.POST.get('password')
        # user=authenticate(request,username=username,password=password)
        # if user:
        #     lgi(request,user)
        #     return redirect(reverse("vote:index"))
        # else:
        #     return render(request,'vote/login.html',{"errors":"登陆失败"})



def logout(request):
    lgo(request)
    return redirect(reverse('vote:login'))


def regist(request):
    if request.method == "POST":
        username=request.POST.get("username")
        password=request.POST.get("password")

    try:
        user=PullsUser.objects.create_user(username=username,password=password)

    except:
        user=None

    if user:
        return redirect(reverse("vote:login"))
    else:
        return render(request,'vote/html',{'errors':'注册失败'})

demo2/templates/vote/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %} {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/css/man.css">

</head>
<body>
    <div class="container">
        {% if request.user and request.user.is_authenticated %}
            当前用户为{{ request.user }} <a href="{% url 'vote:logout' %}">退出</a>
        {% endif %}


        {% block container %}

        {% endblock %}

    </div>



</body>
</html>

demo2/templates/vote/detail.html
{% extends 'vote/base.html' %}
{% block title %}
    <title>问题列表</title>
{% endblock %}

{% block container %}
 <h2>当前问题为{{ desc.desc }}</h2>
        <h3>请投票</h3>
        <ul>
            <form action="{%url 'vote:detail' desc.id%}" method="post">
                {% csrf_token %}
                {% for c in desc.choice_set.all %}
                {% if forloop.counter == 1 %}
                    <li><input checked type="radio" name="choice" value="{{ c.id }}">{{ c.desc }}</li>
                {% else %}
                    <li><input type="radio" name="choice" value="{{ c.id }}">{{ c.desc }}</li>
                {% endif %}
                {% endfor %}

            <input type="submit" value="投票" >
            </form>
        </ul>

{% endblock %}

demo2/templates/vote/index.html
{% extends 'vote/base.html' %}
{% block title %}
    <title>首页</title>
{% endblock %}

{% block container %}
     <h2>问题列表</h2>
        {% if desc %}
            <ul>
                {% for q in desc %}
                    <ol><a href="detail/{{ q.id }}/">{{forloop.counter}} {{q.desc}} </a> </ol>
                {% empty %}

                {% endfor %}
            </ul>
        {% else %}
            <li>没有问题</li>
        {% endif %}



{% endblock %}

demo2/templates/vote/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
<div class="container">

    <div>
        {{errors}}
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#login" aria-controls="login" role="tab" data-toggle="tab">登录</a>
            </li>
            <li role="presentation"><a href="#regist" aria-controls="regist" role="tab" data-toggle="tab">注册</a>
            </li>
        </ul>

        <!-- Tab panes -->
        {% comment %}
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="login">
                <h2>登录</h2>

                <form method="post" action="{% url 'vote:login' %}">
                    <div class="form-group">
                        <label for="username">用户名</label>
                        <input type="text" class="form-control" id="username" placeholder="输入用户名" name="username">
                    </div>
                    <div class="form-group">
                        <label for="password">密码</label>
                        <input type="password" class="form-control" id="password" placeholder="输入密码" name="password">
                    </div>

                    <button type="submit" class="btn btn-default">登录</button>
                </form>
            </div>
            <div role="tabpanel" class="tab-pane" id="regist">
                <h2>注册</h2>

                <form method="post" action="{% url 'vote:regist' %}">
                    <div class="form-group">
                        <label for="registusername">用户名</label>
                        <input type="text" class="form-control" id="registusername" placeholder="输入用户名" name="username">
                    </div>
                    <div class="form-group">
                        <label for="registpassword">密码</label>
                        <input type="password" class="form-control" id="registpassword" placeholder="输入密码" name="password">
                    </div>
                    <div class="form-group">
                        <label for="password2"> 重复密码</label>
                        <input type="password" class="form-control" id="password2" placeholder="输入密码" name="password2">
                    </div>

                    <button type="submit" class="btn btn-default">注册</button>
                </form>
            </div>
        </div>
        {% endcomment %}





        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="login">
                <h2>登录</h2>

                <form method="post" action="{% url 'vote:login' %}">
                    {{form}}
                    <button type="submit" class="btn btn-default">登录</button>
                </form>
            </div>
            <div role="tabpanel" class="tab-pane" id="regist">
                <h2>注册</h2>

                <form method="post" action="{% url 'vote:regist' %}">
                    <div class="form-group">
                        <label for="registusername">用户名</label>
                        <input type="text" class="form-control" id="registusername" placeholder="输入用户名" name="username">
                    </div>
                    <div class="form-group">
                        <label for="registpassword">密码</label>
                        <input type="password" class="form-control" id="registpassword" placeholder="输入密码" name="password">
                    </div>
                    <div class="form-group">
                        <label for="password2"> 重复密码</label>
                        <input type="password" class="form-control" id="password2" placeholder="输入密码" name="password2">
                    </div>

                    <button type="submit" class="btn btn-default">注册</button>
                </form>
            </div>
        </div>

    </div>


</div>

</body>
</html>

demo2/templates/vote/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/css/man.css">

</head>
<body>
    <div class="container">
        <h2>投票结果</h2>
        <h2>当前问题为：{{dest.dest}}</h2>
        <ul>
            {% for c in desc.choice_set.all %}
                <li>{{ c.desc }}：{{c.num}}</li>
            {% endfor %}

        </ul>
        <a href="{% url 'vote:index' %}">跳转首页</a>
    </div>
</body>
</html>