demo1/booktest/urls.py
from django.conf.urls import url
from .import views
app_name='booktest'
urlpatterns = [

    url(r'^$',views.index,name='index'),
    url(r'^list/$',views.list,name='list'),
    url(r'^detail/(\d+)/$',views.detail,name='detail'),
    url(r'^deletehero/(\d+)/$',views.deletehero,name='deletehero'),
    url(r'^addhero/(\d+)/$',views.addhero,name='addhero'),
    # url(r'^login/$',views.login,name='login')
]

demo1/demo1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('booktest/',include('booktest.urls',namespace='booktest')),
]

demo1/booktest/models.py
from django.db import models

# Create your models here.

class BookInfo(models.Model):
    title=models.CharField(max_length=20)
    pub_date=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class HeroInfo(models.Model):
    name=models.CharField(max_length=20)
    gender=models.CharField(max_length=5,choices=( ('man','男'),('woman','女')))
    content=models.CharField(max_length=100)
    book=models.ForeignKey(BookInfo,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

demo1/booktest/views.py
from django.shortcuts import render ,reverse ,redirect
from django.http import HttpResponse,HttpResponseRedirect
# Create your views here.
from django.template import loader
from .models import BookInfo,HeroInfo


def index(request):
    # return HttpResponse('这是首页' "<a href='/booktest/list/'>跳转列表页</a>")
    # 1.获取模板
    temp1=loader.get_template('booktest/index.html')
    # 2.使用模板渲染字典参数
    result=temp1.render({'username':'swy'})
    # 3.将渲染的结果返回
    return HttpResponse(result)

def list(request):
    s="""
    <br>
    <a href='/booktest/detail/1/'>跳转详细页1</a>
    <a href='/booktest/detail/2/'>跳转详细页2</a>
    <a href='/booktest/detail/3/'>跳转详细页3</a>

    
    """
    # return HttpResponse('这是列表页%s' %s)
    temp2=loader.get_template('booktest/list.html')
    books=BookInfo.objects.all()
    result=temp2.render({'book':books})

    return HttpResponse(result)


def detail(request,id):
    # return HttpResponse('这是详情页%s'"<a href='/booktest/'>跳转首页</a>%(id)")
    temp3=loader.get_template('booktest/detail.html')
    book=BookInfo.objects.get(pk=id)
    print(book)
    result=temp3.render({"book":book})
    return HttpResponse(result)


def deletehero(request,id):
    hero=HeroInfo.objects.get(pk=id)
    bookid=hero.book.id
    hero.delete()
    # return HttpResponse('删除成功')

    return redirect(reverse('booktest:detail',args=(bookid,)))

def addhero(request,id):
    book=BookInfo.objects.get(pk=id)
    if request.method=="GET":
    # return HttpResponse('成功')
        return render(request,"booktest/addhero.html",{'book':book})
    elif request.method == "POST":
        name = request.POST.get("username")
        content = request.POST.get("content")
        gender=request.POST.get("gender")
        hero = HeroInfo()
        hero.name = name
        hero.gender=gender
        hero.content = content
        hero.book = book
        hero.save()
        return redirect(reverse("booktest:detail",args=(id,)))

demo1/templates/booktest/addhero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

    <div class="select2-container">
        <h2>当前书籍为：{{ book.title }}</h2>
        <form class="form-horizontal" action="{% url 'booktest:addhero' book.id %} " method="post">
            <div class="form-group">
                <label for="usernamre" class="col-sm-2 control-label">名字</label>
                <div class="col-sm-10">
                    <input type="text" name="username" class="form-control" id="usernamre" placeholder="请输入名字">
                </div>
            </div>
            <div class="form-group">
                <label for="gender" class="col-sm-2 control-label">介绍</label>
                <div class="col-sm-10">
                    <select name="gender" id="gender" class="form-control">
                        <option value="man">男</option>
                        <option value="woman">女</option>
                    </select>

                </div>
            </div>
            <div class="form-group">
                <label for="content" class="col-sm-2 control-label">介绍</label>
                <div class="col-sm-10">
                    <input type="text" name="content" class="form-control" id="content" placeholder="请输入介绍">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">添加</button>
                </div>
            </div>
        </form>

    </div>




<!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
<script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
<!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>

</body>
</html>

demo1/templates/booktest/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>详情页</h2>
    <h3>当前书籍为：{{book.title}}</h3>
    {% if book.heroinfo_set.count %}
        <h3>用有角色</h3>
        <ul>
            {% for hero in book.heroinfo_set.all %}
             <li>{{hero.name}}----{{hero.content}}----<a href="{%  url 'booktest:deletehero' hero.id %}">删除</a> </li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>没有英雄</h3>
    {% endif %}

    <a href="{% url 'booktest:addhero' book.id %}">添加</a>

    {# <a href="/booktest/">跳转首页</a> #}
    <a href="{% url 'booktest:index'  %}">跳转首页</a>


</body>
</html>

demo1/templates/booktest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/css/main.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">

</head>
<body>
    <h2>首页</h2>
    <h3>当前用户：<span class="username" >{{ username }}</span></h3>
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <div style="text-align: center;">
                    <img src="/static/img/1.jpg" alt="..." width="800px" height="400px">
                </div>
                <div class="carousel-caption">
                    ...
                </div>
            </div>
            <div class="item">
                <div style="text-align: center;">
                    <img src="/static/img/2.jpg" alt="..." width="800px" height="400px">
                </div>
                <div class="carousel-caption">
                    ...
                </div>
            </div>
            ...
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    {# <a href="/booktest/list">硬编码跳转到列表</a>  #}
    <a href="{% url 'booktest:list'%}">跳转列表</a>

<!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
<script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
<!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>

</body>
</html>

demo1/templates/booktest/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>书籍列表</h2>
    <ul>
        {% for book in book %}
        <li> <a href="{% url 'booktest:detail' book.id %}"/> {{book.title}}----{{ book.pub_date }}</li>

        {%endfor %}

    </ul>

</body>
</html>