demo4/apps/blog/urls.py
from django.conf.urls import url
from . import views
app_name='blog'
urlpatterns=[
    url('^$',views.IndexView.as_view(),name='index'),
    url(r'single/(\d+)/$',views.singView.as_view(),name='single'),
    url(r'addarticle/$', views.Addarticle.as_view(), name='addarticle'),

]

demo4/demo4/urls.py
from django.contrib import admin
from django.urls import path,include
import xadmin
from django.views.static import serve
from django.conf.urls import url
from .settings import MEDIA_ROOT

# serve用于处理用户上传
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('xadmin/',xadmin.site.urls),
    url(r'^media/(?P<path>.*)$',serve,{'document_root':MEDIA_ROOT}),
    url('ueditor/',include('DjangoUeditor.urls')),
    path('',include('blog.urls',namespace='blog')),
    url('search/',include('haystack.urls'))

]

demo4/apps/blog/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from DjangoUeditor.models import UEditorField

class Ads(models.Model):
    img=models.ImageField(upload_to='ads')
    desc=models.CharField(max_length=20)
    index=models.IntegerField(default=0)

class Category(models.Model):
    title=models.CharField(max_length=20)

class Tag(models.Model):
    title=models.CharField(max_length=20)

class Article(models.Model):
    title=models.CharField(max_length=20)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    create_time=models.DateTimeField(auto_now_add=True)
    update_time=models.DateTimeField(auto_now=True)
    author=models.ForeignKey(User,on_delete=models.CASCADE)
    views=models.IntegerField(default=0)
    # body=models.TextField()
    body=UEditorField(imagePath='articleimg/',width="100%")
    tage=models.ManyToManyField(Tag)

demo4/apps/comment/models.py
from django.db import models
from blog.models import Article
# Create your models here.
class Comment(models.Model):
    name = models.CharField(max_length=20)
    url = models.URLField(blank=True, null=True, default="http://www.baidu.com")
    email = models.EmailField(blank=True, null=True)
    content = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

demo4/apps/blog/forms.py
from django import forms
from .models import Article
from comment.models import Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model=Article
        fields=['title','body']
        widgets={
            'title':forms.TextInput(attrs={'class':'form-conteol'})
        }
        labels={
            'title':'文章标题' ,
            'body':'文章内容'
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields = ['name', 'url','email','content']

demo4/apps/blog/views.py
from django.shortcuts import render,redirect,reverse,get_object_or_404
from django.views.generic import View
from django.http import HttpResponse
from .models import *
from .forms import ArticleForm,CommentForm
from django.core.paginator import Paginator,Page


# Create your views here.
class IndexView(View):
    def get(self,request):
        ads=Ads.objects.all()
        articles=Article.objects.all()
        pagenum=request.GET.get('page')
        pagenum=1 if not pagenum else pagenum
        page=Paginator(articles,1).get_page(pagenum)

        return render(request,'blog/index.html',{'page':page,'ads':ads})

class singView(View):
    def get(self,request,id):
        article=get_object_or_404(Article,pk=id)
        article.views += 1
        article.save()

        cf=CommentForm()

        return render(request,'blog/single.html',locals())
    def post(self,request,id):
        article=get_object_or_404(Article,pk=id)
        cf=CommentForm(request.POST)
        comment=cf.save(commit=False)
        comment.article=article
        comment.save()

        return redirect(reverse('blog:single',args=(article.id,)))

class Addarticle(View):
    def get(self,request):
        af=ArticleForm()
        return render(request,'blog/addarticle.html',locals())
    def post(self,request):
        af=ArticleForm(request.POST)
        if af.is_valid():
            article=af.save(commit=False)
            article.category=Category.objects.first()
            article.author=User.objects.first()
            article.save()
            return redirect(reverse('blog:index'))
        return HttpResponse("添加失败")

demo4/extract_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

demo4/templates/blog/addarticle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title></title>
    {% endblock %}
        <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/static/css/pace.css">
    <link rel="stylesheet" href="/static/css/custom.css">

    <!-- js -->
    <script src="/static/js/jquery-2.1.3.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/pace.min.js"></script>
    <script src="/static/js/modernizr.custom.js"></script>



</head>
<body>
<div id="site-header">
	<div class="container">
		<div class="row">
				<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
								<h1><a href="{% url 'blog:index' %}"><b>博客实战</b></a></h1>
						</div>
				</div><!-- col-md-4 -->
				<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
								<div class="navbar-header">
										<button type="button" id="trigger-overlay" class="navbar-toggle">
												<span class="ion-navicon"></span>
										</button>
								</div>

								<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
										<ul class="nav navbar-nav navbar-right">
												<li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
												<li class="cl-effect-11"><a href="#" data-hover="博客">博客</a></li>
												<li class="cl-effect-11"><a href="#" data-hover="联系">联系</a></li>
										</ul>
								</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
								<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
								<div id="search-form" class="search-form">
										<form role="search" method="get" id="searchform" action="#">
												<input type="search" placeholder="搜索" required>
												<button type="submit"><span class="ion-ios-search-strong"></span></button>
										</form>
								</div>
						</div>
				</div><!-- col-md-8 -->
		</div>
	</div>
</div>
<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {{af.media}}
                <form action="" method="post">
                    {% csrf_token %}

                    <p>文章标题:{{af.title}}</p>
                    <p>文章内容：{{af.body}}</p>
                    <br>
                    <div class="col-md-3">
                        <input type="submit" value="添加" class="form-control">

                    </div>
                </form>

            </main>

        </div>
    </div>
</div>
<div id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2019 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="zzy0371">zzy0371</a>
                    - 由<a href="https://github.com/" title="github" target="_blank">zzy0371</a>修改
                </p>
            </div>
        </div>
    </div>
</div>

<script src="/static/js/script.js"></script>

</body>
</html>

demo4/templates/blog/base.html
<!DOCTYPE html>
{% load my_func %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title></title>
    {% endblock %}
        <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/static/css/pace.css">
    <link rel="stylesheet" href="/static/css/custom.css">

    <!-- js -->
    <script src="/static/js/jquery-2.1.3.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/pace.min.js"></script>
    <script src="/static/js/modernizr.custom.js"></script>



</head>
<body>
<div id="site-header">
	<div class="container">
		<div class="row">
				<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
								<h1><a href="{% url 'blog:index' %}"><b>博客实战</b></a></h1>
						</div>
				</div><!-- col-md-4 -->
				<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
								<div class="navbar-header">
										<button type="button" id="trigger-overlay" class="navbar-toggle">
												<span class="ion-navicon"></span>
										</button>
								</div>

								<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
										<ul class="nav navbar-nav navbar-right">
												<li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
												<li class="cl-effect-11"><a href="#" data-hover="博客">博客</a></li>
												<li class="cl-effect-11"><a href="#" data-hover="联系">联系</a></li>
										</ul>
								</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
								<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
								<div id="search-form" class="search-form">
										<form role="search" method="get" id="searchform" action="/search/">
												<input type="search" placeholder="搜索" required name="q">
												<button type="submit"><span class="ion-ios-search-strong"></span></button>
										</form>
								</div>
						</div>
				</div><!-- col-md-8 -->
		</div>
	</div>
</div>
<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block left %}

                {% endblock %}

            </main>
            <aside class="col-md-4">
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    <ul>r
                        {% getlatestarticles 4 as latestarticles %}

                        {% for i in latestarticles %}

                        <li>
                            <a href="#">{{i.title}}</a>
                        </li>

                        {% endfor %}

                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    <ul>
                        <li>
                            <a href="#">2017 年 5 月</a>
                        </li>
                        <li>
                            <a href="#">2017 年 4 月</a>
                        </li>
                        <li>
                            <a href="#">2017 年 3 月</a>
                        </li>
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    <ul>
                        <li>
                            <a href="#">Django 博客教程 <span class="post-count">(13)</span></a>
                        </li>
                        <li>
                            <a href="#">Python 教程 <span class="post-count">(11)</span></a>
                        </li>
                        <li>
                            <a href="#">Django 用户认证 <span class="post-count">(8)</span></a>
                        </li>
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        <li>
                            <a href="#">Django</a>
                        </li>
                        <li>
                            <a href="#">Python</a>
                        </li>
                        <li>
                            <a href="#">Java</a>
                        </li>
                        <li>
                            <a href="#">笔记</a>
                        </li>
                        <li>
                            <a href="#">文档</a>
                        </li>
                        <li>
                            <a href="#">AngularJS</a>
                        </li>
                        <li>
                            <a href="#">CSS</a>
                        </li>
                        <li>
                            <a href="#">JavaScript</a>
                        </li>
                        <li>
                            <a href="#">Snippet</a>
                        </li>
                        <li>
                            <a href="#">jQuery</a>
                        </li>
                    </ul>
                </div>
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<div id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2019 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="zzy0371">zzy0371</a>
                    - 由<a href="https://github.com/" title="github" target="_blank">zzy0371</a>修改
                </p>
            </div>
        </div>
    </div>
</div>

<script src="/static/js/script.js"></script>

</body>
</html>

demo4/templates/blog/index.html
{% extends 'blog/base.html' %}
{% block title %}
    <title>首页</title>
{% endblock %}


{% block left %}
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            {% for a in ads %}
                {% if forloop.counter == 1 %}
                    <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0 }}" class="active"></li>

                {% else %}
                    <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0 }}"></li>
                {% endif %}

            {% endfor %}


        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            {% for a in ads %}
                {% if forloop.counter == 1 %}
                    <div class="item active">
                <img src="/media/{{a.img}}" alt="...">
                <div class="carousel-caption">
                    <h1>{{a.desc}}</h1>
                </div>
            </div>
                {% else %}
                    <div class="item">
                <img src="/media/{{a.img}}" alt="...">
                <div class="carousel-caption">
                    <h1>{{a.desc}}</h1>
                </div>
            </div>
                {% endif %}

            {% endfor %}


        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>




        {% for i in page.object_list %}
        <article class="post post-{{i.id}}">
        <header class="entry-header">
            <h1 class="entry-title">
                <a href="{% url 'blog:single' i.id %}">{{i.title}}</a>
            </h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{i.category.title}}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="2012-11-09T23:15:57+00:00">{{i.create_time}}</time></a></span>
                <span class="post-author"><a href="#">{{i.author}}</a></span>
                <span class="comments-link"><a href="#">{{i.comment_set.count}} 评论</a></span>
                <span class="views-count"><a href="#">{{i.views}}阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            <p>{{i.body|safe|truncatechars:200}}</p>
            <div class="read-more cl-effect-14">
                <a href="{% url 'blog:single' i.id %}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
            </div>
        </div>
    </article>

        {% endfor %}
     <!-- 简单分页效果
    <div class="pagination-simple">
        <a href="#">上一页</a>
        <span class="current">第 6 页 / 共 11 页</span>
        <a href="#">下一页</a>
    </div>
    -->
    <div class="pagination col-md-11">
                    <ul>
                        {% if page.has_previous %}
                        <li class="col-md-2"><a href="/?page={{page.previous_page_number}}">上一页</a></li>
                        {% endif %}

                        {% for i in page.paginator.page_range %}
                            {% if i == page.number %}
                            <li class="current col-md-1"><a href="/?page={{i}}">{{i}}</a></li>

                            {% else %}
                            <li class="col-md-1"><a href="/?page={{i}}">{{i}}</a></li>
                            {% endif %}
                        {% endfor %}

                        {% comment %}
                        <li class="col-md-1"><a href="">...</a></li>
                        <li class="col-md-1"><a href="">53</a></li>
                        <li class="col-md-1"><a href="">54</a></li>
                        <li class="current col-md-1"><a href="">55</a></li>
                        <li class="col-md-1"><a href="">56</a></li>
                        <li class="col-md-1"><a href="">57</a></li>
                        <li class="col-md-1"><a href="">...</a></li>
                        {% endcomment %}

                        {% if page.has_next %}
                        <li class="col-md-2"><a href="/?page={{page.next_page_number}}">下一页</a></li>
                        {% endif %}
                    </ul>
                </div>
{% endblock %}



</body>
</html>

demo4/templates/blog/single.html
{% extends 'blog/base.html' %}
{% block title %}
    <title>详情</title>
{% endblock %}


{% block left %}
<article class="post post-{{article.id}}">
		<header class="entry-header">
				<h1 class="entry-title">{{article.title}}</h1>
				<div class="entry-meta">
						<span class="post-category"><a href="#">{{article.category.title}}</a></span>
						<span class="post-date"><a href="#"><time class="entry-date"
																											datetime="2012-11-09T23:15:57+00:00">{{article.create_time}}</time></a></span>
						<span class="post-author"><a href="#">{{article.author.username}}</a></span>
						<span class="comments-link"><a href="#">{{article.comment_set.count}} 评论</a></span>
						<span class="views-count"><a href="#">{{article.views}} 阅读</a></span>
				</div>
		</header>
		<div class="entry-content clearfix">
				{{article.body|safe}}
		</div>
</article>
<section class="comment-area" id="comment-area">
		<hr>
		<h3>发表评论</h3>
		<form action="{% url 'blog:single' article.id %}" method="post" class="comment-form">
			{% csrf_token %}
			<div class="row">
						<div class="col-md-4">
								<label for="id_name">名字：</label>
								{{cf.name}}
						</div>
						<div class="col-md-4">
								<label for="id_email">邮箱：</label>
								{{cf.email}}
						</div>
						<div class="col-md-4">
								<label for="id_url">网址：</label>
								{{cf.url}}
						</div>
						<div class="col-md-12">
								<label for="id_content">评论：</label>
								{{cf.content}}</textarea>
								<button type="submit" class="comment-btn">发表</button>
						</div>
				</div>    <!-- row -->
		</form>
		<div class="comment-list-panel">
				<h3>评论列表，共 <span>{{article.comment_set.count}}</span> 条评论</h3>
				<ul class="comment-list list-unstyled">
					{% for i in article.comment_set.all %}
					<li class="comment-item">
						<span class="nickname">{{i.name}}</span>
						<time class="submit-date" datetime="2012-11-09T23:15:57+00:00">{{i.create_time}}</time>
						<div class="text">
							{{i.content}}
						</div>
					</li>
					{% endfor %}

				</ul>
		</div>
</section>
{% endblock %}